headers_single_resource_not_found = [
    "Date",
    "Content-Type",
    "Content-Length",
    "Connection",
    "X-Powered-By",
    "Access-Control-Allow-Origin",
    "Etag",
    "Via",
    "Cache-Control",
    "CF-Cache-Status",
    "Age",
    "Report-To",
    "NEL",
    "Vary",
    "Server",
    "CF-RAY",
]