headers_single_user = [
    "Date",
    "Content-Type",
    "Transfer-Encoding",
    "Connection",
    "X-Powered-By",
    "Access-Control-Allow-Origin",
    "Etag",
    "Via",
    "Cache-Control",
    "CF-Cache-Status",
    "Age",
    "Report-To",
    "NEL",
    "Vary",
    "Server",
    "CF-RAY",
    "Content-Encoding"
]